### ISSUE TITLE
[BUG] Manga-Tagger leaves empty folders after import & tag

### ISSUE THREAD

**Issue by Banh-Canh** [MangaManagerORG/Manga-Tagger#3]
**Manga Tagger Version:** 1.2.0-alpha

**Description of the issue:** Manga-Tagger leaves empty folders after import and tagging all recently added chapters.

**Comment by Jerrk** [comment]
i'm still getting empty folders quite frequently that aren't cleaned up. let me know if you need any logs or such.
![](https://i.imgur.com/PUDB4nN.png)

**Comment by Banh-Canh** [comment]
I'd like some logs about that if you can reproduce this please.

**Comment by Jerrk** [comment]
In my FMD2 favorites tab i highlighted 14 titles and hit "download all"
this is the MantaTagger.log file that was created for the session where these chapters were downloaded and imported.
[MangaTagger.log](https://github.com/Banh-Canh/Manga-Tagger/files/7413118/MangaTagger.log)
3 series had some sort of error while downloading, however "Isekai Dungeon no Renai Jijou" had no issues but the folder was not removed.
![](https://i.imgur.com/Uv2Ja9N.png)

and here are the docker container settings ([unraid](https://i.imgur.com/C0gzW4U.png))

**Comment by Banh-Canh** [comment]
I believe it's because this one manga doesn't have any description on Anilist. Can you confirm that the metadata are present (and correct) in the archive ? And if it other manga that fails like this one have a description on anilist or not ?
Thanks for the feedback, I'll try to fix that

**Comment by Jerrk** [comment]
interesting.
All the titles with empty folders left had neither the cover or comicinfo.xml files in the .cbz archive.
I checked a couple of these empty folders that i've shown above and more.

[Isekai Dungeon no Renai Jijou](https://anilist.co/manga/101685/Isekai-Dungeon-no-Renai-Jijou/)
[The Galactic Navy Officer Becomes an Adventurer](https://anilist.co/manga/106835/Kouchuugun-Shikan-Boukensha-ni-Naru/)
[Bamen Kanmoku-shou ni Natta Hanashi](https://anilist.co/manga/119111/Bamen-Kanmokushou-ni-Natta-Hanashi/)
[Mahouka Koukou no Rettousei: Shiba Tatsuya Ansatsu Keikaku](https://anilist.co/manga/110366/Mahouka-Koukou-no-Rettousei-Shiba-Tatsuya-Ansatsu-Keikaku/)
[Hazure Aka Madoushi wa Kenja Time ni Musou Suru](https://anilist.co/manga/124523/Hazure-Aka-Madoushi-wa-Kenja-Time-ni-Musou-Suru/)
[Aragae! Dark Elf-chan](https://anilist.co/manga/135390/Aragae-Dark-Elfchan/)

all have no description on anilist

[Yong Heng Zhi Zun](https://anilist.co/manga/101513/Yong-Heng-Zhi-Zun/)
[X - Epoch of Dragon](https://anilist.co/manga/103825/X--Epoch-of-Dragon/)
[Shikkokutsukai no Saikyou Yuusha: Nakama Zenin ni Uragirareta node Saikyou no Mamono to Kumimasu ](https://anilist.co/manga/115724/Shikkokutsukai-no-Saikyou-Yuusha-Nakama-Zenin-ni-Uragirareta-node-Saikyou-no-Mamono-to-Kumimasu/)
[Anime Prison School wo Tsukutta Otoko-tachi](https://anilist.co/manga/97001/Anime-Prison-School-wo-Tsukutta-Otokotachi/)
[KILLING ME / KILLING YOU](https://anilist.co/manga/104690/KILLING-ME--KILLING-YOU/)

would also seem to have something in common that causes this issue, not sure what though.

**Comment by Jerrk** [comment]
ok i tried specifically only downloading the above list in a session, this only created 4 empty folders
![](https://i.imgur.com/7vFydT9.png)

and heres the log
[MangaTagger.log](https://github.com/Banh-Canh/Manga-Tagger/files/7447030/MangaTagger.log)

hopefully something can me observed from this

Could it have anything to do with calls to the db if the chapter is already downloaded in the db?
