### ISSUE TITLE
[FEATURE] Volume creation

### ISSUE THREAD

**Issue by Banh-Canh** [MangaManagerORG/Manga-Tagger#4]
Add a settings to enable volume creation: merge multiple chapters (configurable) into one volume.
Or scrape metadata about volumes to create 'official' ones.

**Comment by GlassedSilver** [comment]
I really love this idea! :)

Ideally don't bundle chapters into one big `cbz`, but rather make the volumes at subdirectory level. (this should be an option however I think, some may legitimately prefer either or? Personally, I cannot live without storing chapters in individual `cbz`'s.)

Additionally: Pull cover art based on volume. Mangadex is a very high-quality volume cover art provider btw. :)
Volume cover art would be a single graphic file in `/library/%MANGA%/%Volume%/` - I think most manga reader apps should parse that correctly.

**Comment by ThePromidius** [comment]
I though it was worth mentioning this.

I wanted mangatagger to keep volumes and add it to comicinfo. And so i did in my branch. Rn i focused on having the basic functionality. Would have to touch some code not related and some unit tests but works fine. Let me know if interested and i'll pr the branch with the changes.
if you want to take a look: https://github.com/ThePromidius/Manga-Tagger/tree/features/volume_support

**Comment by GlassedSilver** [comment]
> I though it was worth mentioning this.
> 
> I wanted mangatagger to keep volumes and add it to comicinfo. And so i did in my branch. Rn i focused on having the basic functionality. Would have to touch some code not related and some unit tests but works fine. Let me know if interested and i'll pr the branch with the changes. if you want to take a look: https://github.com/ThePromidius/Manga-Tagger/tree/features/volume_support

Sounds good, is this going to work with chapter fractions/extra chapters? (e.g. Chapter 3.5; Chapter 29.3; Chapter 29.4; ...)

**Comment by ThePromidius** [comment]
Yeah chapter is parsed as always. It just adds Vol.## to the filename and to the comicinfo.xml

**Comment by GlassedSilver** [comment]
> Yeah chapter is parsed as always. It just adds Vol.## to the filename and to the comicinfo.xml

If this could support sorting it into a volume subfolder that'd be amazing!

**Comment by ThePromidius** [comment]
I prefer to have each chapter on its own file. Much better for loading them in a selfhost app.
Technically it should be possible but it's not something I'm going to take time on since i don't see any use for it apart from having less files.

**Comment by GlassedSilver** [comment]
> I prefer to have each chapter on its own file. Much better for loading them in a selfhost app. Technically it should be possible but it's not something I'm going to take time on since i don't see any use for it apart from having less files.

I meant subfolder, not merge all pages into a volume. :)

I still want each chapter to have its own cbz, but for the path to look like:

`%MANGA&/%VOLUME%/%MANGA% %VOLUME% %CHAPTER% %CHAPTERNAME%.cbz`

Chapter and Chapter name both, because it can contain very valuable information, e.g. if a chapter is an edited (uncensored for example) version of an otherwise "duplicate" chapter.

Alternatively, and probably both easier and more robust:
`%MANGA%/%VOLUME%/original-filename.cbz`

(like I pointed out here: https://github.com/Banh-Canh/Manga-Tagger/issues/19#issuecomment-1094281108)

Sorry for those walls of text, but it seems you got comfy with the code and Banh-Canh seems pre-occupied, which is fair, we all have lives after all outside GH. :)

**Comment by ThePromidius** [comment]
Well that can be easily done. I though you meant to have ach chapter on its own subfolder inside the cbz. It could be one serting more in the settings json.
Idk how comfortable Banh-Canh is with pull requests tbh and if he'd add it to this fork tho.


I see you use kavita too you can contact me in the discord if you want.

> Another thing I noticed is that pulling of art is a bit of a hot topic. The general manga art often is for a specific volume or before there are tankobon it's a promotional graphic. However, whilst Kavita supports volumes, if you supply the cover art for the entire series per chapter cbz then all your chapter previews end up being the cover art. It would be cool if the cover art could be loaded specific to the volume and put into the %CHAPTER% directory.

While this is offtopic I'll answer you here. I setup only the cover of the volume to the first chapter of the volume. The rest are untouched. My tool does a good job at setting covers. Letting you know 😉

**Comment by Banh-Canh** [comment]
Hello, I'm ok with pull request and any contribution of course.
But about unifying chapter into volume subfolder: it could mess up with how chapters are added to your reader's library.? I think it does for Komga.

If it can be added as a configurable option I think it's a pretty good idea though.

**Comment by GlassedSilver** [comment]
> Hello, I'm ok with pull request and any contribution of course. But about unifying chapter into volume subfolder: it could mess up with how chapters are added to your reader's library.? I think it does for Komga.
> 
> If it can be added as a configurable option I think it's a pretty good idea though.

Komga is a bad solution for manga anyhow.

Kavita supports volume subfolders.

As for configurable: yes absolutely, and default to off I guess so existing installs don’t break. :)

**Comment by ThePromidius** [comment]
Closed by #23
